name: AWS CodeGuru Reviewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeguru-reviewer:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_CODE_GURU_REVIEWER_ROLE_ARN }}
        aws-region: us-west-1

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        build_path: .
        s3_bucket: ${{ secrets.CODE_GURU_REVIEWER_S3_BUCKET }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: codeguru-results.sarif.json
